// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import domain "github.com/adbourne/website-seacitysoftware/domain"
import mock "github.com/stretchr/testify/mock"

// ConfigService is an autogenerated mock type for the ConfigService type
type ConfigService struct {
	mock.Mock
}

// LoadConfig provides a mock function with given fields:
func (_m *ConfigService) LoadConfig() *domain.AppConfig {
	ret := _m.Called()

	var r0 *domain.AppConfig
	if rf, ok := ret.Get(0).(func() *domain.AppConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppConfig)
		}
	}

	return r0
}
