// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import domain "github.com/adbourne/website-seacitysoftware/domain"
import mock "github.com/stretchr/testify/mock"

// ContactFormService is an autogenerated mock type for the ContactFormService type
type ContactFormService struct {
	mock.Mock
}

// Process provides a mock function with given fields: contactForm
func (_m *ContactFormService) Process(contactForm *domain.ContactForm) error {
	ret := _m.Called(contactForm)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ContactForm) error); ok {
		r0 = rf(contactForm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
