// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import services "github.com/adbourne/website-seacitysoftware/services"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message, fields
func (_m *Logger) Debug(message string, fields services.Fields) {
	_m.Called(message, fields)
}

// Error provides a mock function with given fields: message, fields
func (_m *Logger) Error(message string, fields services.Fields) {
	_m.Called(message, fields)
}

// Info provides a mock function with given fields: message, fields
func (_m *Logger) Info(message string, fields services.Fields) {
	_m.Called(message, fields)
}

// Warn provides a mock function with given fields: message, fields
func (_m *Logger) Warn(message string, fields services.Fields) {
	_m.Called(message, fields)
}
