// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// RecaptchaService is an autogenerated mock type for the RecaptchaService type
type RecaptchaService struct {
	mock.Mock
}

// Verify provides a mock function with given fields: response
func (_m *RecaptchaService) Verify(response string) error {
	ret := _m.Called(response)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
